FROM node:16-alpine
WORKDIR '/app'
COPY ./package.json ./
RUN npm install
#to prevent issue with cached node_modules
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache
COPY . .
CMD ["npm", "run", "start"]
